server:
  port:8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xcx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面

thymeleaf:
  encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    xcx:
      com:
        dao : debug



